[tool.poetry]
name = "server"
version = "0.0.0"
description = "Backend application for resumate"
authors = ["ragarwalll <agarwal.rahul324@gmail.com>"]
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.scripts]
server = "app:application"

[tool.poetry.dependencies]
python = "^3.12"
flask = "^3.0.3"
structlog = "^25.1.0"
python-dotenv = "^1.0.1"
orjson = "^3.10.9"
pygments = "^2.18.0"
pymupdf = "^1.26.3"
pdfminer-six = "^20250506"
pydantic = "^2.11.7"
flask-restx = "^1.3.0"
rapidfuzz = "^3.13.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
black = "^24.10.0"
pylint = "^3.3.1"
pytest-cov = "^6.2.1"

[tool.pytest.ini_options]
testpaths = ["__tests__"]
python_files = ["test_*.py"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
exclude = '^/src/version.py'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''
