ARG NODE_VERSION=20

FROM node:${NODE_VERSION}-slim
LABEL maintainer="Rahul Agarwal <agarwal.rahul324@gmail.com>"

ARG BUN_VERSION=1.0.15

WORKDIR /app

# Install Bun in the specified version
RUN apt update && apt install -y bash curl unzip && \
    rm -rf /var/lib/apt/lists/* && \
    curl https://bun.sh/install | bash -s -- bun-v${BUN_VERSION}

ENV PATH="${PATH}:/root/.bun/bin"

#
# Copy the lock file and app manifest, then install
# the dependencies, including the dev dependencies
#
COPY bun.lockb package.json ./

RUN bun install

# Copy the application sources into the build stage
COPY . .

ENV NODE_ENV="development"
EXPOSE 3000
ENV HOSTNAME=0.0.0.0

CMD ["bun", "dev"]